'use client';

import { Sparkles, FlaskConical, ShieldAlert, Info } from 'lucide-react';

import type { LlmStatus } from '@/lib/llm/types';
import { cn } from '@/lib/utils';

/**
 * Presentational LLM provider status for the simulator. Renders one of four
 * honest states and, for the Groq demo, the remaining shared allowance + a
 * privacy warning. Groq is always described as a *limited* shared demo — never
 * "unlimited", "free", or "production-grade".
 *
 * The status is sanitized server-side (GET /api/llm-status): no key material,
 * key prefixes/suffixes, org info, or raw env ever reaches this component.
 */
export function LlmStatusBanner({ status }: { status: LlmStatus | null }) {
  if (!status) return null;

  if (status.mode === 'gemini-byok') {
    return (
      <Bar tone="mint">
        <Sparkles className="size-3.5 shrink-0" />
        <span>
          <strong>Gemini · Your key.</strong> Real AI responses use your Gemini quota.
        </span>
      </Bar>
    );
  }

  if (status.mode === 'gemini-platform') {
    return (
      <Bar tone="primary">
        <Sparkles className="size-3.5 shrink-0" />
        <span>
          <strong>Platform AI.</strong> Real AI responses are provided by the FlowMind server key.
        </span>
      </Bar>
    );
  }

  if (status.mode === 'groq-demo') {
    const exhausted = status.demoRequestsRemaining <= 0;
    if (exhausted) {
      return (
        <Bar tone="amber">
          <FlaskConical className="size-3.5 shrink-0" />
          <span>
            <strong>Demo allowance reached.</strong> Connect Gemini to continue using real AI
            responses. FlowMind will otherwise use a simulated response.
          </span>
        </Bar>
      );
    }
    return (
      <Bar tone="primary">
        <FlaskConical className="size-3.5 shrink-0" />
        <span>
          <strong>FlowMind Demo AI.</strong> Real AI responses come from a limited shared Groq
          allowance. <strong>{status.demoRequestsRemaining}</strong> demo{' '}
          {status.demoRequestsRemaining === 1 ? 'response' : 'responses'} remaining today ·{' '}
          <span className="opacity-90">Connect Gemini for full access.</span>
          <span className="mt-1 flex items-center gap-1 text-[11px] font-normal opacity-90">
            <ShieldAlert className="size-3 shrink-0" />
            Do not enter sensitive or confidential information into this public prototype.
          </span>
        </span>
      </Bar>
    );
  }

  // simulation
  return (
    <Bar tone="amber">
      <FlaskConical className="size-3.5 shrink-0" />
      <span>
        <strong>Simulation mode.</strong> The response is deterministic and was not generated by an
        external language model. Connect a Gemini key for real AI responses.
      </span>
    </Bar>
  );
}

/**
 * Persistent privacy notice shown while the Groq demo is the active provider —
 * the LLM node prompt leaves FlowMind for Groq to process.
 */
export function LlmPrivacyNotice({ status }: { status: LlmStatus | null }) {
  if (status?.mode !== 'groq-demo') return null;
  return (
    <div className="flex items-start gap-1.5 border-t bg-muted/40 px-5 py-2 text-[11px] text-muted-foreground">
      <Info className="mt-0.5 size-3 shrink-0" />
      <span>
        FlowMind Demo AI sends the LLM node prompt to Groq for processing. Do not use confidential,
        regulated or personal information in this public prototype.
      </span>
    </div>
  );
}

function Bar({
  tone,
  children,
}: {
  tone: 'mint' | 'primary' | 'amber';
  children: React.ReactNode;
}) {
  const tones: Record<typeof tone, string> = {
    mint: 'border-mint/40 bg-mint/10 text-foreground',
    primary: 'border-primary/30 bg-primary/10 text-foreground',
    amber:
      'border-amber-400/50 bg-amber-100 text-amber-900 dark:border-amber-500/40 dark:bg-amber-950/50 dark:text-amber-100',
  };
  return (
    <div
      className={cn(
        'flex shrink-0 items-start gap-2 border-b px-5 py-2 text-xs font-medium',
        tones[tone],
      )}
    >
      {children}
    </div>
  );
}
