/**
 * Deterministic simulated response. The offline demo fallback: no external
 * provider is called, so the same input always yields the same output. Clearly
 * labeled as simulated by the route's metadata (provider 'deterministic',
 * providerMode 'simulation').
 *
 * Client-safe (pure) so tests and the route can share the exact text.
 */

/** Build the deterministic reply text for a prompt pair. */
export function deterministicReply(systemPrompt: string, userPrompt: string): string {
  const sys = systemPrompt ? `(system: ${systemPrompt.slice(0, 80)}...) ` : '';
  return (
    `${sys}Simulation mode - this is a deterministic response, not generated by an ` +
    `external language model. Connect a Gemini key for real AI answers. You asked: ` +
    `"${userPrompt.slice(0, 200)}"`
  );
}

/** Split a full reply into word-ish pieces so the SSE path can "stream" it. */
export function chunkDeterministic(text: string): string[] {
  const out: string[] = [];
  const words = text.split(/(\s+)/);
  let buf = '';
  for (const w of words) {
    buf += w;
    if (buf.length >= 8) {
      out.push(buf);
      buf = '';
    }
  }
  if (buf) out.push(buf);
  return out;
}
