// Placeholder — regenerated by `pnpm db:types` (see package.json).
// Do NOT hand-edit. Committed so the repo typechecks before a local Supabase
// stack has been started.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
