'use client';

import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { ArrowRight, Sparkles, Workflow, Database, Zap } from 'lucide-react';

const features = [
  {
    icon: Workflow,
    title: 'Visual Graph Runtime',
    description:
      'Design conversation flows on a visual canvas. Hybrid deterministic + agentic execution.',
  },
  {
    icon: Sparkles,
    title: 'Story Builder',
    description:
      'Describe your assistant in plain English. Get a complete graph generated by Gemini.',
  },
  {
    icon: Database,
    title: 'Knowledge Grounding',
    description:
      'Upload PDFs, crawl websites. RAG with citations using pgvector + hybrid search.',
  },
  {
    icon: Zap,
    title: 'One-Click Deploy',
    description:
      'Publish a version, get an embeddable widget. Multi-environment with rollback.',
  },
];

export function Hero() {
  return (
    <div className="relative overflow-hidden bg-gradient-to-b from-background via-background to-muted/30">
      {/* Decorative gradient orbs */}
      <div className="pointer-events-none absolute inset-0 overflow-hidden">
        <div className="absolute -left-40 top-20 h-96 w-96 rounded-full bg-violet-500/20 blur-3xl" />
        <div className="absolute -right-40 top-40 h-96 w-96 rounded-full bg-fuchsia-500/20 blur-3xl" />
        <div className="absolute left-1/3 top-1/2 h-96 w-96 rounded-full bg-pink-500/10 blur-3xl" />
      </div>

      <div className="relative mx-auto max-w-6xl px-6 py-24 sm:py-32">
        <div className="text-center">
          <div className="mb-6 inline-flex items-center gap-2 rounded-full border bg-background/60 px-4 py-1.5 text-xs font-medium backdrop-blur">
            <span className="relative flex h-2 w-2">
              <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-400 opacity-75" />
              <span className="relative inline-flex h-2 w-2 rounded-full bg-emerald-500" />
            </span>
            v0.1 — Vertical slice live
          </div>

          <h1 className="text-5xl font-bold tracking-tight sm:text-7xl">
            <span className="bg-gradient-to-r from-violet-600 via-fuchsia-600 to-pink-600 bg-clip-text text-transparent">
              FlowMind
            </span>
          </h1>
          <p className="mx-auto mt-4 max-w-2xl text-balance text-lg text-muted-foreground sm:text-xl">
            Figma for conversational AI + a debugger for AI behavior. Visual
            graph runtime, knowledge grounding, deep tracing, one-click deploy.
          </p>

          <div className="mt-10 flex flex-wrap items-center justify-center gap-3">
            <Button asChild size="xl" variant="gradient">
              <Link href="/dashboard">
                Open Dashboard <ArrowRight className="size-5" />
              </Link>
            </Button>
            <Button asChild size="xl" variant="outline">
              <Link href="#features">See features</Link>
            </Button>
          </div>
        </div>

        <div
          id="features"
          className="mt-24 grid gap-6 sm:grid-cols-2 lg:grid-cols-4"
        >
          {features.map((f) => (
            <div
              key={f.title}
              className="group relative overflow-hidden rounded-xl border bg-card p-6 shadow-sm transition-all hover:shadow-md hover:-translate-y-0.5"
            >
              <div className="mb-4 inline-flex h-10 w-10 items-center justify-center rounded-lg bg-gradient-to-br from-violet-500/10 to-fuchsia-500/10 text-violet-600">
                <f.icon className="size-5" />
              </div>
              <h3 className="font-semibold">{f.title}</h3>
              <p className="mt-1 text-sm text-muted-foreground">
                {f.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
